//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace anbardari
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class tbl_checklist
    {
        public int id { get; set; }

		[DisplayName("سمت")]
        public Nullable<int> sematId { get; set; }
		
		[DisplayName("بخش")]
        public Nullable<int> bakhshId { get; set; }
		
        [DisplayName("پرسنل")]
        public Nullable<int> personId { get; set; }

        [DisplayName("عنوان")]
        public Nullable<int> questionId { get; set; }

        [DisplayName("امتیاز")]
        public Nullable<int> rate { get; set; }

        [DisplayName("سال")]
        public Nullable<int> year { get; set; }

        [DisplayName("ماه")]
        public Nullable<int> month { get; set; }
    }
}
