//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace anbardari
{
    using System;
    using System.Collections.Generic;
	using System.ComponentModel;
    
    public partial class tbl_productAnbar
    {
        public int Id { get; set; }
		[DisplayName("کد کالا")]
        public int productId { get; set; }
		[DisplayName("انبار/بخش")]
        public int anbarId { get; set; }
		[DisplayName("تعداد")]
        public Nullable<int> number { get; set; }
		[DisplayName("حداقل درخواست")]
        public Nullable<int> minOrder { get; set; }
		[DisplayName("حداکثر درخواست")]
        public Nullable<int> maxOrder { get; set; }
		[DisplayName("آخرین ماه درخواست")]
        public Nullable<int> lastYearOrder { get; set; }
		[DisplayName("آخرین سال درخواست")]
        public Nullable<int> lastMonthOrder { get; set; }
		[DisplayName("دوره زمانی")]
        public Nullable<int> days { get; set; }
    }
}
