//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace anbardari
{
    using System;
    using System.Collections.Generic;
	using System.ComponentModel;
    
    public partial class tbl_orderProduct
    {
        public int Id { get; set; }
		
		[DisplayName("کد کالا")]
        public Nullable<int> productId { get; set; }
		[DisplayName("مسئول")]
        public Nullable<int> personId { get; set; }
		[DisplayName("شماره درخواست")]
        public int orderId { get; set; }
		[DisplayName("تعداد درخواستی")]
        public Nullable<int> numberDarkhasti { get; set; }
		[DisplayName("تعداد تحویلی")]
        public Nullable<int> number { get; set; }
		[DisplayName("قیمت")]
        public Nullable<double> price { get; set; }
		[DisplayName("توضیحات")]
        public string description { get; set; }
		[DisplayName("فعال")]
        public bool state { get; set; }
        public string barcode { get; set; }
    }
}
