//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace anbardari
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class tbl_order
    {
        public int Id { get; set; }

        [DisplayName("شماره درخواست")]
        public Nullable<int> orderId { get; set; }

        [DisplayName("تاریخ")]
        public Nullable<int> date { get; set; }

        [DisplayName("زمان")]
        public Nullable<int> time { get; set; }

        [DisplayName("مبدا")]
        public Nullable<int> anbar1 { get; set; }

        [DisplayName("مقصد")]
        public Nullable<int> anbar2 { get; set; }

        [DisplayName("مبلغ")]
        public Nullable<double> price { get; set; }

        [DisplayName("وضعیت")]
        public int state { get; set; }

        [DisplayName("بارکد")]
        public string barcode { get; set; }
    }
}
