//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
// </auto-generated>
//------------------------------------------------------------------------------

namespace anbardari
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class tbl_personel
    {
        public int id { get; set; }
		
		[DisplayName("سمت")]
        public Nullable<int> sematId { get; set; }
		
		[DisplayName("بخش")]
        public Nullable<int> bakhshId { get; set; }

        [DisplayName("نام")]
        public string name { get; set; }

        [DisplayName("نام خانوادگی")]
        public string family { get; set; }

        [DisplayName("نام پدر")]
        public string father { get; set; }

        [DisplayName("شماره ملی")]
        public string meli { get; set; }

        [DisplayName("تاریخ تولد")]
        public Nullable<int> bdate { get; set; }

        [DisplayName("عکس")]
        public string pic { get; set; }

        [DisplayName("امضا")]
        public string emza { get; set; }

        [DisplayName("فعال")]
        public bool active { get; set; }
    }
}
