//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace anbardari
{
    using System;
    using System.Collections.Generic;
	using System.ComponentModel;
    
    public partial class tbl_product
    {
        public int Id { get; set; }
		[DisplayName("انبار")]
        public int anbarId { get; set; }
		[DisplayName("دسته بندی")]
        public Nullable<int> category { get; set; }
		[DisplayName("کد کالا")]
        public string codeKala { get; set; }
		[DisplayName("نام کالا")]
        public string name { get; set; }
		[DisplayName("تولید")]
        public string date1 { get; set; }
		[DisplayName("انقضا")]
        public string date2 { get; set; }
		[DisplayName("سریال")]
        public string serialNumber { get; set; }
		[DisplayName("بارکد")]
        public string barcode { get; set; }
		[DisplayName("حداقل دما")]
        public Nullable<int> temperetureMin { get; set; }
		[DisplayName("حداکثر دما")]
        public Nullable<int> temperetureMax { get; set; }
		[DisplayName("حداقل درخواست")]
        public Nullable<int> minOrder { get; set; }
		[DisplayName("حداکثر درخواست")]
        public Nullable<int> maxOrder { get; set; }
		[DisplayName("فعال")]
        public bool active { get; set; }
    }
}
